RickCarlino/KoalaCards

- components/play-button.tsx
- components/record-button.tsx
- pages/_study_reducer.ts
- pages/study.tsx
- server/routers/get-next-quizzes.ts
- server/routers/main.ts
- utils/fetch-lesson.ts
The current review scheme was a prototype that mostly happened on accident as I researched bigger problems.
Now that my understanding of the problem space has improved, I have re-written the way sessions work.
This is the long term solution and it will mostly be incremental fixes and changes from here on out.
> New structure for review sessions

- components/play-button.tsx
- pages/_study_reducer.ts
- pages/study.tsx
- server/routers/perform-exam.ts
* Fix bug where wrong audio would play when transitions from dictation to listening tests.
* Remove audio playback in reducer hack
* Show users an explanation of why they failed the quiz, along with what they said.
> More exam performance improvements.

- components/record-button.tsx
- pages/_study_reducer.ts
- pages/study.tsx
- server/routers/perform-exam.ts
- utils/fetch-lesson.ts
* Globally rename "quiz type" to "lesson type"
* Simplify the way the quiz reducer presents tests.
* Improve UI when quiz answer is incorrect.
* Improve grading prompts.
> September 9th Updates

- .gitignore
- pages/import.tsx
- pages/study.tsx
- phrases.tsv
- server/routers/main.ts
- speech-export-prototype.ts
- utils/ingest-phrases.ts
- utils/random-new.ts
It really was a fun experiment using GPT-4 to generate example sentences, and I will continue to do it for my personal studies. I don't think it is ready for mass use yet and in the name of getting things stable, I have decided to revert the feature for now.
I will probably release the feature I use later as a CLI tool.
> Make imports generic again

- speech-export-prototype.ts
- utils/fetch-lesson.ts
Update the scheduler to sort cards by repetition count, then by due date. This way, mature cards are reviewed first.
> Update scheduler query

- README.md
- pages/import.tsx
- pages/study.tsx
- phrases.tsv
- server/routers/get-next-quizzes.ts
- speech-export-prototype.ts
- utils/fetch-lesson.ts
* We have a clubhouse group- if you want to talk to me about KoalaSRS development, please join.
* Update the review scheduler to only show new cards once current cards have been reviewed.
* Show total cards due/total cards in study UI.
* Update the card importer validator to be less strict.
> September 16 2023 Updates

- components/record-button.tsx
- pages/_study_reducer.ts
- pages/study.tsx
- utils/srs.ts
* Bug fix: Stop the user from flagging an item while recording.
* Improvement: Make reviews more frequent during the first 5 review sessions.
* Do fewer dictation tests (just 1, not 3)
* Make the "coaching" dialog box an obnoxious salmon color :fish:
> Bugfixes, UI updates, SRS algorithm tweaks

- package.json
- pages/_app.tsx
- pages/_authed.tsx
- pages/_nav.tsx
- pages/_study_reducer.ts
- pages/import.tsx
- phrases.tsv
Better nav bar, less weird styling issues.
Quizzes are now shuffled rather than being determined by repetition count.
This improves the experience when you have many cards due at the same time, since it can be very boring to have 10 cards with the exact quiz type all at once.
> Quiz Shuffling, UI Updates

- .gitignore
Also hoping this auto-builds the prod instance :crossed_fingers:
> Gitignore updates

- Dockerfile
- package.json
- pages/study.tsx
- utils/_study_reducer.ts
* Better progression for new cards
* Run migrations on deployment.
* Remove a debug thing I left in.
> Minor Updates

- README.md
- utils/srs.test.ts
- utils/srs.ts
> Fix off-by-one error in spaced repettion algorithm.

- README.md
- pages/study.tsx
- server/routers/get-next-quizzes.ts
- utils/_study_reducer.ts
- utils/fetch-lesson.ts
- utils/ingest-phrases.ts
* Fix bug where incorrect cards were counted as "new" in the deck overview display.
* Show number of lapses on the deck overview display.
> Bug fix, display update

- components/quiz-failure.tsx
- pages/api/auth/[...nextauth].ts
- pages/api/trpc/[trpc].ts
- pages/faucet.tsx
- pages/study.tsx
- prisma/migrations/20231020113818_userslastseen/migration.sql
- prisma/schema.prisma
- server/routers/get-next-quizzes.ts
- server/routers/main.ts
- utils/_study_reducer.ts
- utils/fetch-lesson.ts
- utils/srs.test.ts
- utils/srs.ts
- utils/study-reminder.ts
* Formatting fixes.
* Auto flag after 4 lapses
* Add a "lastSeen" column to users table
* Begin writing an email practice reminder function.
* Delete old SSML shenanigans.
> 20 October Updates

- pages/import.tsx
- prisma/migrations/20231022013349_addmoretimestampstocardtable/migration.sql
- prisma/migrations/20231022014848_remove_phrase_table/migration.sql
- prisma/migrations/20231022015451_more_removals/migration.sql
- prisma/schema.prisma
- server/routers/main.ts
- server/routers/perform-exam.ts
This PR adds more timestamps to the "Cards" table so that I can add analytics add a later date (cards per day, new cards this month, etc...)
> Better timestamps on cards

- pages/study.tsx
- server/routers/perform-exam.ts
- utils/_study_reducer.ts
Oops, I made an error in `gradeAndUpdateTimestamps` last night.
> Scheduling bugfix

- components/record-button.tsx
- pages/import.tsx
- server/routers/get-next-quizzes.ts
- server/routers/perform-exam.ts
- utils/_study_reducer.ts
- utils/fetch-lesson.ts
- utils/transcribe.ts
* Explicitly delete audio temp files after use.
* Change session deck order. Cards with lapses have highest priority, then regular cards, then new cards.
* New card progression is easier now.
* Dead code removal
* Bug fix for "blinking" during long sessions.
* Fix import loader.
* Only playback audio half the time. It was taking too long. Long term maybe we will have a "playback ratio" setting.
> Tuesday Updates

- components/quiz-failure.tsx
- example.env
- pages/api/prometheus.ts
- server/routers/get-next-quizzes.ts
- server/routers/perform-exam.ts
- utils/transcribe.ts
* Secure prom endpoint
* Re-write prompts
* Change hideous wrong answer color
* run formatter
> Oct 26 updates

- components/card-table.tsx
- components/quiz-failure.tsx
- example.env
- pages/api/prometheus.ts
- pages/cards/[card_id].tsx
- pages/import.tsx
- pages/study.tsx
- server/routers/get-next-quizzes.ts
- server/routers/main.ts
- server/routers/perform-exam.ts
- utils/_study_reducer.ts
- utils/counter.ts
- utils/fetch-lesson.ts
I am slowly change the terms "English" and "Korean" to "term" and "definition" to eventually support multilingual-ness.
> Graduated grading

- pages/_nav.tsx
- pages/create.tsx
- server/routers/perform-exam.ts
- utils/fetch-lesson.ts
* "Create Cards" page doesn't just sit there while stuff is loading.
* Bug fix: dictation test was giving 100% correct grade 100% of time.
* New cards are drawn from deck in FIFO order.
> Updates, NOV 5

- components/record-button.tsx
- server/routers/perform-exam.ts
There is no need to use an LLM in cases where the quiz is 100% correct.
This PR updates logic to speed things up, reduce costs, reduce errors, etc...
> Don't call OpenAI on exact matches

- pages/study.tsx
- server/auth-helpers.ts
- server/routers/delete-card.ts
- server/routers/edit-card.ts
- server/routers/edit-user-settings.ts
- server/routers/get-one-card.ts
- server/routers/perform-exam.ts
- utils/_study_reducer.ts
- utils/clean-string.ts
- utils/error-report.ts
- utils/fetch-lesson.ts
- utils/transcribe.ts
* Improve Whisper prompt.
* Improve "exact match" algorithm to consider sentences with a levenshtein distance of "1" exact matches.
* Add a unified central error reporter.
* Make some minor improvements to allow for asynchronous grading.
> Multiple Minor Improvements

- pages/study.tsx
- pages/user.tsx
- server/routers/perform-exam.ts
- server/trpc.ts
- utils/_study_reducer.ts
- utils/fetch-lesson.ts
* Bug fix: Newer failures clobber older failure when rendering.
* Adjust GPT-4 prompt temperature.
* Fix card draw query/logic.
* Fix bug where a card that was awaiting a grade would get re-inserted into the deck while waiting for OpenAI API. Most common during peak hours.
> Numerous Bug Fixes

- components/card-table.tsx
- pages/study.tsx
- server/auth-helpers.ts
- server/routers/bulk-create-cards.ts
- server/routers/get-all-cards.ts
- server/routers/perform-exam.ts
- utils/create-cards-from-text.ts
This is the final v2 release. v3 will **NOT** be backwards compatible and you will need to manually upgrade by exporting from v2 and importing the file into a new account on the v3 server.
Please contact me if you are affected by this change. At this point, I am only aware of a few users who are using the app and I have reached out to them personally.
> Final v2 Release

- example.env
- pages/study.tsx
- prisma/schema.prisma
- server/quiz-evaluators/listening.ts
- server/quiz-evaluators/speaking.ts
- server/quiz-evaluators/types.ts
- server/routers/bulk-create-cards.ts
- server/routers/get-next-quizzes.ts
- server/routers/grade-quiz.ts
- server/routers/import-cards.ts
- server/routers/rollback-grade.ts
- utils/fetch-lesson.ts
- utils/openai.ts
Minor fixes from the last release.
> v3.0.0 Release

- koala/quiz-evaluators/speaking.ts
- package-lock.json
- package.json
- pages/_app.tsx
- pages/api/auth/[...nextauth].ts
- pages/auth/email.tsx
- pages/study.tsx
On iOS mobile it was very difficult to log in because the email client would attempt to load a preview of the URL. This would invalidate the login token before the user could actually use the app. There was also a small issue with the penalty timer.
> Login and penalty timer bugfixes

- koala/card-table.tsx
- koala/routers/delete-card.ts
- pages/_nav.tsx
- pages/cards.tsx
This is a quick hack but it works for now.
> Add delete button back

- README.md
- koala/fetch-lesson.ts
- koala/openai.ts
- koala/quiz-failure.tsx
- koala/routers/get-playback-audio.ts
- koala/routers/grade-quiz.ts
- koala/routers/main.ts
- koala/settings-provider.tsx
- koala/study_reducer.ts
- pages/_app.tsx
- pages/api/auth/[...nextauth].ts
- pages/auth/email.tsx
- pages/create.tsx
- pages/study.tsx
Thanks for the sweet domain name idea, GPT-4.
The app now lives in https://app.koala.cards
> KoalaSRS is now Koala.Cards

- koala/fetch-lesson.ts
- koala/routers/get-next-quizzes.ts
- koala/settings-provider.tsx
- koala/study_reducer.ts
- pages/study.tsx
- pages/user.tsx
The new review scheduler does not start speaking tests until you have passed a listen quiz for the card at least three times.
I found it too frustrating to practice listening and speaking in parallel.
> New Review Scheduling Retrieval, "Win %" stat

- koala/fetch-lesson.ts
- koala/quiz-evaluators/speaking.ts
- pages/create.tsx
- pages/study.tsx
* Better header verbiage
* Fix hotkeys
* Better review sort order
> Minor updates and bug fixes

- koala/fetch-lesson.ts
- koala/openai.ts
- koala/quiz-evaluators/speaking.ts
I turned this off during a big refactor. Forgot to add it back.
> Bring back "Max Cards per Day" setting

- README.md
- example.env
- koala/create-cards-from-text.ts
- koala/fetch-lesson.ts
- koala/image.ts
- koala/openai.ts
- koala/quiz-evaluators/listening.ts
- koala/quiz-evaluators/speaking.ts
- koala/quiz-evaluators/types.ts
- koala/routers/faucet.ts
- koala/routers/get-next-quizzes.ts
- koala/routers/get-one-card.ts
- koala/routers/get-playback-audio.ts
- koala/routers/grade-quiz.ts
- koala/routers/import-cards.ts
- koala/shared-types.ts
- koala/speech.ts
- koala/storage.ts
- koala/study_reducer.ts
- koala/transcribe.ts
- package-lock.json
- package.json
- pages/create.tsx
- pages/faucet.tsx
- pages/study.tsx
- pages/user.tsx
- prisma/schema.prisma
Cards add DALL-E illustrations automatically to ease memorization.
> Add lesson illustrations

- Dockerfile
- koala/openai.ts
- koala/quiz-evaluators/evaluator-utils.ts
- koala/quiz-evaluators/listening.ts
- koala/quiz-evaluators/speaking.ts
- koala/routers/get-one-card.ts
- koala/routers/grade-quiz.ts
- koala/routers/import-cards.ts
- koala/speech.ts
- next.config.js
- package-lock.json
- package.json
- pages/cards/[card_id].tsx
- pages/faucet.tsx
- prisma/migrations/20240503014236_add_blob_id_to_cards/migration.sql
* Increase retention rate
* Show image in card overview page.
* Improve illustration prompt to use Koalas instead of people.
> Updates to card illustrations

- koala/evenly-distribute.ts
- koala/fetch-lesson.ts
- koala/openai.ts
- koala/quiz-evaluators/index.ts
- koala/routers/export-cards.ts
- koala/routers/get-next-quizzes.ts
- koala/routers/grade-quiz.ts
- koala/routers/import-cards.ts
- koala/routers/parse-cards.ts
- koala/storage.ts
- koala/study_reducer.ts
- pages/api/auth/[...nextauth].ts
- pages/study.tsx
* **Big change:** New cards will now be more "Anki like" in that the first review will usually happen the same day. I was previously ignoring cards for the first 24 hours.
* Rename "Fail" to "Again".
* Bug fix related to USER_GAVE_UP
* DRY up grading logic and exception handling.
> Scheduler Updates

- koala/fetch-lesson.ts
- koala/image.ts
- koala/openai.ts
- koala/quiz-evaluators/listening.ts
- koala/quiz-evaluators/speaking.ts
- package-lock.json
- package.json
- prisma/migrations/20240922150739_add_speaking_corrections/migration.sql
- prisma/schema.prisma
* Increase auto flag stability to 365
* Try new illustration prompt for short sentences and single word cards.
* New grammar correction feature.
> Grammar corrections.

- koala/grammar.ts
- koala/openai.ts
- koala/play-audio.tsx
- koala/quiz-evaluators/speaking.ts
- koala/routes/get-mirroring-cards.ts
- koala/routes/main.ts
- pages/mirror.tsx
- prisma/migrations/20241001010920_add_mirror_repetition_count/migration.sql
- prisma/schema.prisma
I am starting work on v4. This is probably one of the last (or the last) update to v3.
> v3 Final Updates

- koala/autopromote.ts
- koala/decks/decks-with-review-info.ts
- koala/equivalence.ts
- koala/fetch-lesson.ts
- koala/grammar-ng.ts
- koala/grammar.ts
- koala/image.ts
- koala/is-approved-user.ts
- koala/review/listening-quiz.tsx
- koala/review/review-over.tsx
- koala/review/review-page.tsx
- koala/settings-provider.tsx
- koala/storage.ts
- koala/transcribe.ts
- koala/translate.ts
- koala/trpc-routes/calculate-scheduling-data.ts
- koala/trpc-routes/create-remix-cards.ts
- koala/trpc-routes/remix.ts
- pages/cards/[card_id].tsx
- pages/create.tsx
- pages/faucet.tsx
- pages/review.tsx
- pages/review/[deckId].tsx
Some feedback:
* Example sentence generation does not create enough content. => increase to 25
* Card creation is confusing => Added a description (for now, need long term solution)
* Don't know when lesson will end => added progress bar.
> More user feedback

- koala/equivalence.ts
- koala/fetch-failure-types.ts
- koala/fetch-failures.ts
- koala/fetch-lesson.ts
- koala/grammar-ng.ts
- koala/grammar.ts
- koala/remix-button.tsx
- koala/review/feedback-row.tsx
- koala/review/review-over.tsx
- koala/review/review-page.tsx
- koala/trpc-routes/calculate-scheduling-data.ts
- koala/trpc-routes/edit-card.ts
- koala/trpc-routes/get-next-quizzes.ts
- koala/trpc-routes/import-cards.ts
- koala/trpc-routes/remix.ts
- pages/cards.tsx
- pages/create-raw.tsx
- pages/repair.tsx
- prisma/migrations/20250110011358_add_failure_timestamp_to_card/migration.sql
- prisma/schema.prisma
CSV upload
"Repair" page (/repair)
GPT-o1-preview remixes
Card fetching overhaul
Scheduler tweaks for new cards.
> Multiple new features

- koala/generate-speech-url.ts
- koala/image.ts
- koala/storage.ts
**Disclaimer**: I don't have a GCS account so i don't actually know if this works with the existing setup. It looks like a one to one replacement to me but worth a test
I plan to self host this and use AWS services so creating interfaces i can work with. I may or may not merge in the full AWS changes later but at least it leaves the door open for you to use something else in the future anyway
> feat: Add storage interface for compatibility with other services

- koala/fetch-lesson.ts
- koala/grammar.ts
- koala/hooks/use-media-recorder.ts
- koala/image.ts
- koala/input-flood/InputFloodLesson.tsx
- koala/play-audio.tsx
- koala/review/index.tsx
- koala/review/lesson-steps/quiz-card.tsx
- koala/review/lesson-steps/remedial-outro.tsx
- koala/review/reducer.ts
- koala/settings-provider.tsx
- koala/utils/play-beep.ts
- pages/review/[deckId].tsx
After some thought, I have decided to pivot away from a multilingual Koala Cards. This means that moving forward, the app will focus on Korean exclusively on Korean. This will simplify several aspects of the design and allow me to focus on more targeted LLM prompts, as well as a adding curated content.
I will create a tag/release of this version for folks who are self hosting forks of the app. Please fork off of this version if you are using Koala for languages other than Korean.
> v7.1.0 - Final Multilingual Version
